server:
    servlet:
        context-path: "/hs-kleinanzeigen"
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/KLEINANZEIGEN?serverTimezone=UTC
        username: root
        password: start01
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: none
            use-new-id-generator-mappings: true
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        generate-ddl: false
        properties:
            hibernate:
                format_sql: true
    liquibase:
        change-log: classpath:liquibase-changeLog.xml
management:
    endpoints:
        web:
            exposure:
                include: info, health, metrics
endpoints:
    metrics:
        enabled: true


